<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="2" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2019-08-05T15:21:30Z" name="Suite" finished-at="2019-08-05T15:22:12Z" duration-ms="41798">
    <groups>
    </groups>
    <test started-at="2019-08-05T15:21:30Z" name="Test" finished-at="2019-08-05T15:22:12Z" duration-ms="41798">
      <class name="com.assure.qa.testcases.LoginPageTest">
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.assure.qa.testcases.LoginPageTest@2638011]" started-at="2019-08-05T15:21:30Z" name="setUp" finished-at="2019-08-05T15:21:40Z" duration-ms="9463" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginPageTitleTest()[pri:1, instance:com.assure.qa.testcases.LoginPageTest@2638011]" started-at="2019-08-05T15:21:40Z" name="loginPageTitleTest" finished-at="2019-08-05T15:21:40Z" duration-ms="37" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginPageTitleTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.assure.qa.testcases.LoginPageTest@2638011]" started-at="2019-08-05T15:21:40Z" name="tearDown" finished-at="2019-08-05T15:21:41Z" duration-ms="934" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.assure.qa.testcases.LoginPageTest@2638011]" started-at="2019-08-05T15:21:41Z" name="setUp" finished-at="2019-08-05T15:21:51Z" duration-ms="10573" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="isAssureElementsDisplayedAndEnabled()[pri:2, instance:com.assure.qa.testcases.LoginPageTest@2638011]" started-at="2019-08-05T15:21:51Z" name="isAssureElementsDisplayedAndEnabled" finished-at="2019-08-05T15:21:52Z" duration-ms="846" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- isAssureElementsDisplayedAndEnabled -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.assure.qa.testcases.LoginPageTest@2638011]" started-at="2019-08-05T15:21:52Z" name="tearDown" finished-at="2019-08-05T15:21:53Z" duration-ms="1109" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.assure.qa.testcases.LoginPageTest@2638011]" started-at="2019-08-05T15:21:53Z" name="setUp" finished-at="2019-08-05T15:22:04Z" duration-ms="10369" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="loginTest()[pri:3, instance:com.assure.qa.testcases.LoginPageTest@2638011]" started-at="2019-08-05T15:22:04Z" name="loginTest" finished-at="2019-08-05T15:22:11Z" duration-ms="7435" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [Hello, Abhilashaa1] but found [Hello, Abhilashaa]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Hello, Abhilashaa1] but found [Hello, Abhilashaa]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at com.assure.qa.testcases.LoginPageTest.loginTest(LoginPageTest.java:77)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.assure.qa.testcases.LoginPageTest@2638011]" started-at="2019-08-05T15:22:11Z" name="tearDown" finished-at="2019-08-05T15:22:12Z" duration-ms="986" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.assure.qa.testcases.LoginPageTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
